name: Publish
on:
  release:
    types: [released]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: publish
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.pages_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public --foreground-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: cp dist/index.iife.js jcbhmr-md-html.min.js
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: jcbhmr-md-html.min.js
      - uses: actions/configure-pages@v3
      - run: npm run docs:prepack
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/dist
      - uses: actions/deploy-pages@v2
