name: Publish
on:
  release:
    types: [released]
  workflow_dispatch:
permissions: write-all
concurrency: publish
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  add-assets:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: npm pack
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/index.iife.js
          asset_name: jcbhmr-md-html.min.js
  publish-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - uses: actions/configure-pages@v3
      - run: npm run docs:prepack
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/dist
      - uses: actions/deploy-pages@v2
        id: deploy-pages
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: spenserblack/actions-wiki@v0.1.1
        with:
          wiki-directory: wiki
          token: x:${{ secrets.GITHUB_TOKEN }}
