name: Publish
on:
  release:
    types: [released]
permissions:
  contents: write
  pages: write
  id-token: write
concurency:
  group: publish
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.pages_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - uses: actions/configure-pages@v3
      - run: npm run docs:prepack
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/dist
      - uses: actions/deploy-pages@v2
      - run: npm publish --access public --foreground-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
