name: Test
on:
  push:
    branches: [main]
    paths: ["*.json", "*.ts", "src/**", "test/**", .github/workflows/test.yml]
  pull_request:
    branches: [main]
    paths: ["*.json", "*.ts", "src/**", "test/**", .github/workflows/test.yml]
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: npm test
